import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from "../components/Card";
import Banner from "../components/Banner";
import coffeeStoresData from "../data/coffee-stores.json"

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores : coffeeStoresData
    }, // will be passed to the page component as props
  }
}
const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  // console.log("props: ", props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       
      <main className={styles.main}>
        <Banner />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero image"
          />
        </div>
        {props.coffeeStores.length > 0 && (
                <>
                  <h2 className={styles.heading2}>Toronto Stores</h2>
                    <div className={styles.cardLayout}>
                    { 
                        props.coffeeStores.map((coffeeStore) => {

                            return <Card  
                              key = {coffeeStore.id}
                              name={coffeeStore.name}
                              imgUrl={coffeeStore.imgUrl}
                              href={`/coffee-store/${coffeeStore.id}`}

                            />
                        })

                    }

                    </div>
                </>
          )}
       </main>
      </main>
    </>
  )
}
